
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "40300:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
